CODON_AA={'TTT':'F','TTC':'F',
          'TTA':'L','TTG':'L','CTT':'L','CTC':'L','CTA':'L','CTG':'L',
          'ATT':'I','ATC':'I','ATA':'I',
          'ATG':'M',
          'GTT':'V','GTC':'V','GTA':'V','GTG':'V',
          'TCT':'S','TCC':'S','TCA':'S','TCG':'S','AGT':'S','AGC':'S',
          'CCT':'P','CCC':'P','CCA':'P','CCG':'P',
          'ACT':'T','ACC':'T','ACA':'T','ACG':'T',
          'GCT':'A','GCC':'A','GCA':'A','GCG':'A',
          'TAT':'Y','TAC':'Y',
          'CAT':'H','CAC':'H',
          'CAA':'Q','CAG':'Q',
          'AAT':'N','AAC':'N',
          'AAA':'K','AAG':'K',
          'GAT':'D','GAC':'D',
          'GAA':'E','GAG':'E',
          'TGT':'C','TGC':'C',
          'TGG':'W',
          'CGT':'R','CGC':'R','CGA':'R','CGG':'R','AGA':'R','AGG':'R',
          'GGT':'G','GGC':'G','GGA':'G','GGG':'G',
          'TAA':'*','TAG':'*','TGA':'*',
         }

codon_AA={'ttt':'F','ttc':'F',
          'tta':'L','ttg':'L','ctt':'L','ctc':'L','cta':'L','ctg':'L',
          'att':'I','atc':'I','ata':'I',
          'atg':'M',
          'gtt':'V','gtc':'V','gta':'V','gtg':'V',
          'tct':'S','tcc':'S','tca':'S','tcg':'S','agt':'S','agc':'S',
          'cct':'P','ccc':'P','cca':'P','ccg':'P',
          'act':'T','acc':'T','aca':'T','acg':'T',
          'gct':'A','gcc':'A','gca':'A','gcg':'A',
          'tat':'Y','tac':'Y',
          'cat':'H','cac':'H',
          'caa':'Q','cag':'Q',
          'aat':'N','aac':'N',
          'aaa':'K','aag':'K',
          'gat':'D','gac':'D',
          'gaa':'E','gag':'E',
          'tgt':'C','tgc':'C',
          'tgg':'W',
          'cgt':'R','cgc':'R','cga':'R','cgg':'R','aga':'R','agg':'R',
          'ggt':'G','ggc':'G','gga':'G','ggg':'G',
          'taa':'*','tag':'*','tga':'*',
         }

start_codon = ['ATG']

stop_codon = ['TAA', 'TAG', 'TGA']
